---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
  - name: update apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include: tasks/productivity-tools.yml
    - include: tasks/nvim-setup.yml
