- name: Installing cargo crates
  become: true
  shell: cargo install bat du-dust ripgrep exa fd-find tokei procs
  environment:
    PATH: "/home/jquirky/.cargo/bin;/usr/local/bin:/user/bin:/bin"
    RUSTUP_HOME: "/home/jquirky/.rustup"
    CARGO_HOME: "/home/jquirky/.cargo"
  tags:
    - install
    - cargo
